### ISSUE TITLE
Error refreshing patches

### ISSUE THREAD

**Issue by tsuliwaensis** [ungoogled-software/ungoogled-chromium-macos#138]
When I follow the instructions on refreshing the patches, it returns an error when it runs `push -a --refresh`. 

````
Applying patch core/inox-patchset/0001-fix-building-without-safebrowsing.patch
can't find file to patch at input on line 3
````

Can I ignore this or do I need to use `quilt remove`? 

Thank you!

**Comment by Cubik65536** [comment]
I can't reproduce this issue in my local environment. Try to update the git submodule first, redownload and retry the patch refresh.

**Comment by tsuliwaensis** [comment]
I want to learn how to do it. That's all.

**Comment by tsuliwaensis** [comment]
> When I follow the instructions on refreshing the patches, it returns an error when it runs `push -a --refresh`.
> 
> ```
> Applying patch core/inox-patchset/0001-fix-building-without-safebrowsing.patch
> can't find file to patch at input on line 3
> ```
> 
> Can I ignore this or do I need to use `quilt remove`?
> 
> Thank you!

I did that and still have the issue. I think it might be a directory issue. When I run `quilt patch -f` it returns

````
touch: .pc/core/inox-patchset/0001-fix-building-without-safebrowsing.patch~refresh: No such file or directory
mkdir: .pc/core/inox-patchset: No such file or directory
Patch core/inox-patchset/0001-fix-building-without-safebrowsing.patch appears to be empty; applied
````

However, the file does exist and located at `/ungoogled-chromium-macos/ungoogled-chromium/patches`

**Comment by Cubik65536** [comment]
You should not ignore it nor `quilt remove` without knowing exactly what it does - if you do know, you should not do that even more because, long story short, it's a part of the ungoogled-chromium submodule and you shouldn't touch it here.

Delete your ungoogled chromium directory, follow the build procedure (you don't have to change for any tag, use what's on `master`):

``` bash
git clone --recurse-submodules https://github.com/ungoogled-software/ungoogled-chromium-macos.git
cd ungoogled-chromium-macos
./build.sh
```

it should work.

If you DO want to try to refresh the patch, follow the same procedure above without running the `./build.sh`, or, if you have already done it, delete the `build` directory. Then follow what have been told in README, it should work.

You actually will not "learn" much from it because nothing will happen (as every patch is working) and you are just copy pasting every command from README.

**Comment by tsuliwaensis** [comment]
I trie

> You should not ignore it nor `quilt remove` without knowing exactly what it does - if you do know, you should not do that even more because, long story short, it's a part of the ungoogled-chromium submodule and you shouldn't touch it here.
> 
> Delete your ungoogled chromium directory, follow the build procedure (you don't have to change for any tag, use what's on `master`):
> 
> ```shell
> git clone --recurse-submodules https://github.com/ungoogled-software/ungoogled-chromium-macos.git
> cd ungoogled-chromium-macos
> ./build.sh
> ```
> 
> it should work.
> 
> If you DO want to try to refresh the patch, follow the same procedure above without running the `./build.sh`, or, if you have already done it, delete the `build` directory. Then follow what have been told in README, it should work.
> 
> You actually will not "learn" much from it because nothing will happen (as every patch is working) and you are just copy pasting every command from README.

I tried that and it worked. Third time's a charm, I guess. Thank you for all your help!
