### ISSUE TITLE
A small suggestion for the Release Notes

### ISSUE THREAD

**Issue by 577** [ungoogled-software/ungoogled-chromium-macos#146]
Since the release title already includes the version and timestamp, it might be unnecessary to repeat this information in the release body, especially since the two timestamps do not match.

![ScreenShot_20240128_hJkbuelfpBd4gihF](https://github.com/ungoogled-software/ungoogled-chromium-macos/assets/46293356/8d48292e-8061-4848-9ccc-4bf5613164bd)

Simply delete these two lines.

https://github.com/ungoogled-software/ungoogled-chromium-macos/blob/4853bf036f660e1e5eeae52577613031d12b814b/.github/scripts/github_generate_release_note.sh#L17-L18

**Comment by Cubik65536** [comment]
Yeah it is an unexpected problem to have it mismatched (I introduced this bug and haven't found it) and I do plan to remove these in the next update.

My plan is to just remove entirely the epoch timestamp from the release (from tag, title, and body), and also just use the `chromium_version` + `ungoogled_revision` (in this case, just the `121.0.6167.85-1.1`) for both the tag and the release title, so that it behaves in the same way as the other repos in the org.

Any opinions on this? /cc @networkException @PF4Public

**Comment by networkException** [comment]
yep, I'm definitely in favor of removing the timestamp. I'm not entirely sure if they were added because CI was unstable or frequent rebuilds were needed, though

**Comment by Cubik65536** [comment]
> yep, I'm definitely in favor of removing the timestamp. I'm not entirely sure if they were added because CI was unstable or frequent rebuilds were needed, though

For now, we shouldn't need to rerun CIs unless we're changing the CI script and just want to test it. And I don't see any cases where there will be rebuilds (with the old script, it's possible that multiple releases will be created, it won't happen again).

I will make this change in the next update then.

**Comment by claudiodekker** [comment]
> yep, I'm definitely in favor of removing the timestamp. I'm not entirely sure if they were added because CI was unstable or frequent rebuilds were needed, though

They were added in https://github.com/ungoogled-software/ungoogled-chromium-macos/pull/92, perhaps @kramred has any recollection of it if they're around?
