### ISSUE TITLE
Issue with 1Password and Notarized Builds

### ISSUE THREAD

**Issue by ronaldho** [ungoogled-software/ungoogled-chromium-macos#207]
With the new Notarized builds, the 1Password extension should work with ungoogle-chromium, however the extension keeps saying the following: "You're asked to re-enter your password because Chrome has an update available." – I've tried both the homebrew and the direct binary with no difference.
<img width="387" alt="Screenshot 2024-11-24 at 11 34 03 PM" src="https://github.com/user-attachments/assets/8472dc0b-92ef-4e94-87de-ef8eaabfbd82">

I followed the instructions [here](https://github.com/claudiodekker/ungoogled-chromium-macos?tab=readme-ov-file#q-even-with-this-version-of-chromium-added-to-1passwords-trusted-browsers-the-extension-wont-auto-unlock-why) to copy over the native messaging hosts file already.

Any ideas @claudiodekker ? FWIW Claudio's builds didn't have this problem

**Comment by Cubik65536** [comment]
Do you have Chrome installed while copying the native messaging hosts files? What is the terminal output when you followed the installation instruction?

**Comment by ronaldho** [comment]
I just found the solution after reading through Claudio's notes again, which led me to this blog post: https://1password.community/discussion/140735/extending-support-for-trusted-web-browsers

The key was that I had added Claudio's chromium build to 1Password previously, and it must have retained the signature. Once I removed it and re-added it, it seems to have solved it.

**Comment by kitschpatrol** [comment]
@ronaldho Thanks for your insights on this issue and sorry to open it back up — I just wanted to ask if you are using the Nightly build channel of 1Password, or the Production channel?

I'm not seeing the option to add trusted browsers in the 1Password desktop app UI, this is with the latest production build 81056028:

![Screenshot 2024-12-22 at 12 57 22 of 1Password - All Items — 1Password@2x](https://github.com/user-attachments/assets/83dddee5-7370-4ff7-800a-712c29fb0c2c)

The 1Password discussion thread you linked suggests this was a Nightly feature, but that thread's over a year old so I'd hope this feature would have made it to the Production channel by now?

**Comment by ronaldho** [comment]
Sorry for the delayed reply. I am on the same build but I have the additional section below the button where it says "Connect to Additional Browsers". Maybe try a uninstall/reinstall? and if not maybe reach out to 1Password support

**Comment by jonesnc** [comment]
I hit the same `Connection problem` on notarized ungoogled-chromium for macOS. The issue was native-messaging host registration: 1Password had created the host manifest for Google Chrome, but not for Chromium.

Related context: https://github.com/claudiodekker/ungoogled-chromium-macos?tab=readme-ov-file#q-even-with-this-version-of-chromium-added-to-1passwords-trusted-browsers-the-extension-wont-auto-unlock-why

The relevant files were:

```
~/Library/Application Support/Google/Chrome/NativeMessagingHosts/com.1password.1password.json
~/Library/Application Support/Chromium/NativeMessagingHosts/com.1password.1password.json
```

Chromium was missing the second file. The extension logs showed Specified native messaging host not found after trying com.1password.1password and com.1password.1password7.

Copying the manifest fixed it:

```bash
mkdir -p ~/Library/Application\ Support/Chromium/NativeMessagingHosts
cp ~/Library/Application\ Support/Google/Chrome/NativeMessagingHosts/com.1password.1password.json \
  ~/Library/Application\ Support/Chromium/NativeMessagingHosts/com.1password.1password.json
```

After restarting Chromium and re-adding it in 1Password’s browser settings, the connection worked for me.
