### ISSUE TITLE
Update to 77

### ISSUE THREAD

**Issue by Zoraver** [ungoogled-software/ungoogled-chromium-macos#24]
I have a working build of ungoogled-chromium-macos 77.0.3865.90, but it has one key caveat: it requires manually setting the `enable_swiftshader` gn flag to `true`; ungoogled-chromium sets it to `false`. 

Chromium 77 appears to require egl to be enabled. When building Chromium for macOS, it appears that enabling egl depends on enabling swiftshader (on Linux, egl can be enabled without enabling swiftshader). In the build that I have working, I do not apply `swiftshader.patch` and set `enable_swiftshader` to `true`.

The best way to resolve this that I can see is to remove the `enable_swiftshader` line from `flags.gn` in ungoogled-chromium and make whether it is set to `true` or `false` a platform specific flag.

**Comment by Eloston** [comment]
@kramred Technically yes, you can re-enable it in `flags.macos.gn`. But IMO that is a bad design choice, because then you'd need to keep multiple files in mind (`flags.macos.gn` and `flags.gn`) to figure out what the proper value for a flag is. If it only shows up once, then what you see it set to in any file must be what its value is.

I'll just move `enable_swiftshader` out of `flags.gn` and into the platform specific flags.
