### ISSUE TITLE
Chromium v83 - Keychain popup

### ISSUE THREAD

**Issue by specter78** [ungoogled-software/ungoogled-chromium-macos#53]
I am getting the following pop everytime chromium is started. This error didn't occur in v81.

<img width="546" alt="Screenshot " src="https://user-images.githubusercontent.com/40606342/86890500-075c7900-c11b-11ea-8dfc-eb8a85e9617b.png">

**Comment by kramred** [comment]
I get the same warning. I usually click "Always Allow" so the new version has permanent access – but as I build the binaries (for sharing) I might be more likely to trust them.

At one point I moved the signing in `build.sh` before the packaging, can't remember if I got the keychain warning in that case.  
I've uploaded another release for [83.0.4103.116-1.2](https://github.com/kramred/ungoogled-chromium-binaries/releases/tag/83.0.4103.116-1.2) where the binary was signed before packing, maybe you could try that first to see if it also leads to a keychain popup?

**Comment by specter78** [comment]
Tried the updated version and I’m still getting the same pop up. 

Also I got the network connection pop up on first launch. Not able to reproduce after subsequent launches.

**Comment by kramred** [comment]
Thanks for testing the second version.

We're (currently) not using any official developer account to sign the binaries or disk image, that's why Gatekeeper and other macOS security measures cannot verify the "authenticity" of new releases.
Missing notarisation may give additional warnings…

I would argue that programs that you've compiled from source deserve the highest trust (as long as you trust your compiler 😉 ).

Any kind of anti virus/malware can never operate on that level; although it would be nice to have a formal prove to cite (there should be one)

If you trust the binaries provided by third parties you can give them access to your keychain (and click "always allow" for each new major release)

Alternatively, if you have the resources you can compile the binary yourself – the instructions are quite thorough. You will still need to manually give them access to your keychain though (except if you have an official developer account and sign them).

**Comment by Eloston** [comment]
Closing because question looks answered. Signing is discussed in https://github.com/Eloston/ungoogled-chromium/issues/240.
