### ISSUE TITLE
How to set the latest chromium version source for building UGC?

### ISSUE THREAD

**Issue by AshH2O** [ungoogled-software/ungoogled-chromium-macos#71]
I have set up most of the things for building it but I would like to use the latest version of chromium to build it. Can I manually set them? And if so, how?

(I'm a newbie so pls help me out with this stupid question)

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently and probably lost its significance — closing.
If you have any more information to add, let us know.

**Comment by Cubik65536** [comment]
Just an answer, if you're still interested in this: Yes and **NO**. What you can build with this repo is definitely the latest **stable** Chromium (or almost the latest, if either ungoogled-chromium core hasn't updated or this repo wasn't in sync with the core). If you want to build dev (unstable) Chromium, even if you can manually change the configuration file to force the version, I do expect these (or even the ungoogled-chromium core) patches to fail and prevent you from building anything because there might be changes in Chromium that breaks the patches (unless you write your own patches to make everything works).

**Comment by ako256** [comment]
Hi, thanks for replying, I did not know back then that I couldn't build chromium on 4 gb ram and a dual core intel i5.
