### ISSUE TITLE
changing secure dns (DoH) settings in one profile affects all profiles

### ISSUE THREAD

**Issue by sneak** [ungoogled-software/ungoogled-chromium-macos#86]
Version 92.0.4515.131 (Official Build, ungoogled-chromium) (x86_64)

macOS 12.2 (21D49)

**Comment by kramred** [comment]
Can reproduce with `98.0.4758.80 (Official Build, ungoogled-chromium) (x86_64)`

You may want to upgrade to the current version as v92 contains a lot of known vulnerabilities.

This may be a general issue of ungoogled-chromium, i.e. not specific to the macOS version. You may want to post an issue in the [main ungoogled-chromium repo](https://github.com/Eloston/ungoogled-chromium) as I probably won't be addressing this in the near future and it seems the macOS repo is somehow abandoned or somehow migrated to my builds… which should be addressed in another issue (by me)

**Comment by sneak** [comment]
92.0... is the latest available for download from the link on

**Comment by sneak** [comment]
Nevermind, found the download link on Homebrew's site.  If the binaries provided by you are available for direct download, why not link them from the README?

**Comment by kramred** [comment]
> Nevermind, found the download link on Homebrew's site. If the binaries provided by you are available for direct download, why not link them from the README?

Because this is mostly done manually by volunteers in their free time and the focus is on getting a working build and all the other things tend to keep falling off the plate.

Also, most/all binaries are not considered "official", although there are the [Automated or maintained builds](https://github.com/Eloston/ungoogled-chromium#automated-or-maintained-builds).

But, for example, for the v98 `macOS_arm64` builds I needed a newer version of some parts of the compiler, which I build in a traceable/reproducible way and documented in the build. But this would have also been a vector to e.g. inject malicious code that probably would have gone unnoticed for quite some time.

What I'm trying to say is that just because something like `brew` is listed in the [Automated or maintained builds](https://github.com/Eloston/ungoogled-chromium#automated-or-maintained-builds) doesn't mean it would be difficult to poison these binaries, as they are provided by only one person (and in `brew` they are added/maintained by even other persons). And I don't know if someone would continuously audit all the build scripts.

And I guess as with most volunteer projects the [bus factor](https://en.wikipedia.org/wiki/Bus_factor) is a considerable risk here, too.

**Comment by sneak** [comment]
Offtopic for this thread now but please email me at sneak@sneak.berlin if I can assist in build tooling, compute resources, bandwidth/hosting, mirrors, documentation updates, or anything else of the like.  I'd like to contribute time and resources to the project.

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently and probably lost its significance — closing.
If you have any more information to add, let us know.
